export default [
  {
    title: 'Podcasts',
    tags: ['React Native', 'Firebase', 'CSS in JS'],
    timeline: 'November 2020 - Present',
    image: 'podcast',
    link: 'https://github.com/singhshemona/podcast',
    pitch: 'A platform to consume Podcasts in a more engaging manner.',
  },
  {
    title: 'Broadening Recommendations',
    tags: ['React', 'Python'],
    timeline: 'January 2021 - Present',
    image: 'recommend',
    link: 'https://github.com/singhshemona/recommend',
    pitch: 'How might we eliminate the bumpers of confirmation bias that our current recommendation engines enforce?',
  },
  {
    title: 'Animations Library',
    tags: ['React', 'SCSS'],
    timeline: 'February 2020 - November 2020',
    image: 'animations',
    link: 'https://github.com/singhshemona/animate',
    pitch: 'Easy to adapt, (accessible and performant) animation templates.',
  },
  {
    title: 'HomeGrade',
    tags: ['React', 'Emotion'],
    timeline: 'April 2019 - April 2020',
    image: 'homegrade',
    link: 'https://github.com/homegrade/HomeGrade',
    pitch: 'Creating a more approachable way to assess a home\'s value.',
  },
  {
    title: 'Makerpaper',
    tags: ['HTML', 'SCSS'],
    timeline: 'November 2018 - December 2019',
    image: 'makerpaper',
    link: 'https://github.com/makerpaper/makerpaper.github.io',
    pitch: 'A mechanism for artists to more easily package and ship their work.',
  },
];
