export default [
  {
    title: 'Broadening Recommendations',
    tags: ['React', 'Python'],
    timeline: 'Jan 2021 - Present',
    image: 'recommend',
    link: 'https://github.com/singhshemona/recommend',
    pitch: 'Eliminating the bumpers of confirmation bias in current recommendation engines.',
  },
  {
    title: 'Traveling Capsule',
    tags: ['React Native'],
    timeline: 'Feb 2021 - Present',
    image: 'capsule',
    link: 'https://github.com/singhshemona/capsule',
    pitch: 'Enables traveling light and expressing style to be mutually inclusive.',
  },
  {
    title: 'Animations Library',
    tags: ['React', 'SCSS'],
    timeline: 'Feb 2020 - Nov 2020',
    image: 'animations',
    link: 'https://github.com/singhshemona/animate',
    pitch: 'Easily adaptable, accessible and performant animation templates.',
  },
  {
    title: 'Redux Course',
    tags: ['React', 'Redux'],
    timeline: 'May 2020 - Aug 2020',
    image: 'course',
    link: 'https://scrimba.com/playlist/pNpEbsP',
    pitch: 'A breakdown of simple uses for Redux with React to build upon.',
  },
  {
    title: 'HomeGrade',
    tags: ['React', 'Emotion'],
    timeline: 'Apr 2019 - Apr 2020',
    image: 'homegrade',
    link: 'https://github.com/homegrade/HomeGrade',
    pitch: 'Creating a more approachable way to assess a home\'s value.',
  },
  {
    title: 'Makerpaper',
    tags: ['HTML', 'SCSS'],
    timeline: 'Nov 2018 - Dec 2019',
    image: 'makerpaper',
    link: 'https://github.com/makerpaper/makerpaper.github.io',
    pitch: 'A mechanism for artists to more easily package and ship their work.',
  },
];
